import 'package:bmi_calculator/pages/bmiBody.dart';
import 'package:bmi_calculator/pages/splash.dart';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class Terms extends StatefulWidget {
  const Terms({Key? key}) : super(key: key);

  @override
  State<Terms> createState() => _TermsState();
}

class _TermsState extends State<Terms> {
  bool isAgree = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        backgroundColor: Colors.blue,
        title: Text("Terms & Conditions"),
        centerTitle: true,
      ),
      body: SingleChildScrollView(
        child: Column(
          // mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.end,
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Container(
              height: MediaQuery.of(context).size.height * 0.7,
              width: MediaQuery.of(context).size.height * 0.7,
              margin: EdgeInsets.all(10),
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(10),
                color: Colors.blue.shade100,
              ),
              padding: EdgeInsets.all(20),
              child: ListView(
                shrinkWrap: true,
                children: [
                  Text(
                    'Welcome to the terms and conditions section for the BMI calculator. These terms and conditions govern your use of the BMI calculator and any associated services provided by the BMI calculator provider. By using the BMI calculator, you agree to these terms and conditions. If you do not agree with these terms and conditions, you should not use the BMI calculator. Please read these terms and conditions carefully before using the BMI calculator. If you have any questions or concerns, please contact the BMI calculator provider.\n\n'
                    '1. The BMI calculator is intended to provide an estimate of an individual\'s body mass index (BMI) based on their height and weight. It is not a substitute for professional medical advice or diagnosis, and it is not intended for use in the diagnosis or treatment of any medical condition.\n\n'
                    '2. The BMI calculator is available to anyone who is 18 years of age or older and is not intended for use by individuals who are pregnant, breastfeeding, or have a medical condition that affects their weight.\n\n'
                    '3. The BMI calculator provides a reasonable estimate of an individual\'s BMI, but it may not be accurate for athletes or individuals with a high muscle mass. Users should consult a healthcare professional for a more accurate assessment of their BMI.\n\n'
                    '4. The BMI calculator collects only the user\'s height and weight information. No other personal information is collected or stored. User data and privacy are protected in accordance with applicable data protection laws.\n\n'
                    '5. The information collected by the BMI calculator is used solely to generate an estimate of the user\'s BMI. It is not shared with any third party.\n\n'
                    '6. The use of the BMI calculator is subject to the following limitations: users should provide accurate height and weight information, use the calculator appropriately, and not rely solely on the results generated by the calculator for making medical or lifestyle decisions.\n\n'
                    '7. There is no liability for errors or inaccuracies in the results generated by the BMI calculator. Users should not rely solely on the results generated by the BMI calculator for making medical or lifestyle decisions.\n\n'
                    '8. Users are responsible for their use of the BMI calculator, and they agree to indemnify and hold harmless the BMI calculator provider and its affiliates, directors, officers, employees, agents, and licensors from any claims, damages, or losses arising out of or related to their use of the calculator.\n\n'
                    '9. These terms and conditions may be changed at any time at the discretion of the BMI calculator provider. Users are encouraged to review these terms periodically to ensure they are aware of any changes.\n\n'
                    '10. By using the BMI calculator, users agree to these terms and conditions. If they do not agree with these terms and conditions, they should not use the BMI calculator.\n\n'
                    'Thank you for reading these terms and conditions for the BMI calculator. By using the calculator, you acknowledge that you have read, understood, and agreed to these terms and conditions. If you have any questions or concerns about these terms and conditions, please contact the BMI calculator provider.',
                    style: TextStyle(color: Colors.black, fontSize: 15),
                  ),
                ],
              ),
            ),
            Card(
              child: CheckboxListTile(
                onChanged: (_) {
                  setState(() {
                    isAgree = !isAgree;
                  });
                },
                value: isAgree,
                title: Text("I accept all the terms & conditions."),
                activeColor: Colors.blue,
              ),
            ),
            Padding(
              padding: const EdgeInsets.only(right: 5.0),
              child: ElevatedButton(
                onPressed: isAgree == true
                    ? () async {
                        var sharedPref = await SharedPreferences.getInstance();
                        sharedPref.setBool(SplashState.KEYLOGIN, true);
                        Navigator.pushReplacement(
                          context,
                          MaterialPageRoute(
                            builder: (context) => BmiBody(),
                          ),
                        );
                      }
                    : null,
                child: Text("Next"),
                style: ElevatedButton.styleFrom(
                  disabledBackgroundColor: Colors.blueAccent,
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}
